Revert "Use python3-multicorn instead of postgresql-13-python3-multicorn"
This reverts commit 1285ebd6d4321f4637db7355f156be6c7512ae50.

    ERROR:  could not open extension control file "/usr/share/postgresql/13/extension/multicorn.control": No such file or directory

The version of multicorn that is installed is not correct